name: Exchange Rate CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'T9/Exchange rate/requirements.txt'

    - name: Run tests
      run: |
        cd 'T9/Exchange rate'
        set PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest tests/ -v